#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Keybindings
# <C-r> -> incremental history search
bindkey '^r' history-incremental-search-backward

# Aliases
## mpv
alias a='mpv --no-video'
alias v='mpv -fs'

## all-in neovim
alias vim=nvim
